#!/bin/bash
#   aSquidguard - Full Squidguard directory 
#
#   Copyright (C) Edwin Enrique Flores Bautista <loquitoslack@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#   RELEASE: 20120518

#### Define Variables y Directorios 
#/bin/bash
domain=${1:?'No se admiten dominios nulos'}
categorie=$2
Draiz=/var/lib/squidguard/db 
Dtmp=/tmp
